name: main
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@main
        with:
          command: lint
          config: .github/config/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          # from https://github.com/yannh/kubernetes-json-schema
          - v1.20.15
          - v1.21.13
          - v1.22.10
          # - v1.23.7
          # - v1.24.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # tag=v3.0.2
        with:
          fetch-depth: 0
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  release:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
      - kubeval-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@main
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  artifacts:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: checkout artifacts branch
        uses: actions/checkout@v3
        with:
          ref: artifacts
      - name: git setup
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
      - name: download artifacts
        run: |
          gh release list | awk '{print$1}' | while read line; do gh release download $line || true; done
          git add .
          git commit -m ":robot: [github actions actor] update artifact list"
          git push
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: generate updated index.yaml
        run: |
          helm repo index . --url "https://raw.githubusercontent.com/gritzkoo/helm-charts/artifacts/"
      - name: persist index.yaml
        uses: actions/upload-artifact@v2
        with:
          name: gh-pages
          path: ./index.yaml
          if-no-files-found: error
  index:
    name: index-update
    runs-on: ubuntu-latest
    needs:
      - artifacts
    steps:
      - name: chekcout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: git setup
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
      - uses: actions/download-artifact@v2
        with:
          name: gh-pages
      - name: commit new index.yaml
        run: |
          if [[ $(git diff) ]];
          then
            git add index.yaml
            git commit -m "[ci skip] :robot: [github actions actor] - update index.yaml"
            git push
          else
            echo "nothing to do!!!"
          fi
