name: main
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@main
        with:
          command: lint
          config: .github/config/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          # from https://github.com/yannh/kubernetes-json-schema
          - v1.20.15
          - v1.21.13
          - v1.22.10
          # - v1.23.7
          # - v1.24.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # tag=v3.0.2
        with:
          fetch-depth: 0
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  release:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
      - kubeval-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@main
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
