name: releaser
on:
  release:
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout artifacts branch
        uses: actions/checkout@v3
        with:
          ref: artifacts
      - name: git setup
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
      - name: download artifacts
        run: |
          gh release list | awk '{print$1}' | while read line; do gh release download $line || true; done
          git add .
          git commit -m ":robot: [github actions actor] update artifact list"
          git push
