name: releaser
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout artifacts branch
        uses: actions/checkout@v3
        with:
          ref: artifacts
      - name: git setup
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
      - name: download artifacts
        run: |
          gh release list | awk '{print$1}' | while read line; do gh release download $line || true; done
          git add .
          git commit -m ":robot: [github actions actor] update artifact list"
          git push
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: generate updated index.yaml
        run: |
          helm repo index . --url "https://raw.githubusercontent.com/gritzkoo/helm-charts/artifacts/"
      - name: persist index.yaml
        uses: actions/upload-artifact@v2
        with:
          name: gh-pages
          path: ./index.yaml
          if-no-files-found: error
  index:
    name: index-update
    runs-on: ubuntu-latest
    steps:
      - name: chekcout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: git setup
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
      - uses: actions/download-artifact@v2
        with:
          name: gh-pages
      - name: commit new index.yaml
        run: |
          if [[ $(git diff) ]];
          then
            git add index.yaml
            git commit -m "[ci skip] :robot: [github actions actor] - update index.yaml"
            git push
          else
            echo "nothing to do!!!"
          fi
      # - name: update index.yaml links
      #   run: |
      #     sed -E -i "s|https\:\/\/github\.com\/gritzkoo\/helm\-charts\/releases\/download\/[A-Z_a-z.0-9-]+\/|https://raw.githubusercontent.com/gritzkoo/helm-charts/artifacts/|g"  index.yaml
      #     if [[ $(git diff) ]];
      #     then
      #       git add index.yaml
      #       git commit -m "[ci skip] :robot: [github actions actor] - update index.yaml"
      #       git push
      #     else
      #       echo "nothing to do!!!"
      #     fi
